[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_dapp = "6V2o2cBPFaa3ZFAipQgU1nGemSM6n4i2tkR5bzg7Z2M8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --timeout 1000000 tests/**/*.ts"
